services:
  - type: web
    name: multi-agent-rag
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: DATABASE_URL
        value: postgres://postgres:CtAxQBmMcWbEFaoyDadeEJyJthhLkUMD@gondola.proxy.rlwy.net:22503/railway

